### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by MarcoArdito** [VTECRM/vtenext#16]
Hi,

Readme.md says you wish to "provide a FREE OPEN SOURCE solution" to also avoid "Lock in" 
but the license.txt  says "VTECRM hereby grants Customer a limited, non-exclusive license to **install, deploy and use** the Software", then "To acquire the Software, Customer **must** register with VTECRM and provide the requested business information."... 

is this an old license file, related to a not FREE OPEN SOURCE version, or is it still active and up to date?
if not, which kind of license are you going to adopt? what will change from those term, and how?

**Comment by davidegiarolo** [comment]
Hi Marco, the license is up to date. Is the one used both for business and free version. The difference is that if you use the free version you must follow AGPL3 licensing rules, otherwise for the business version you are more near to MPL licensing (you are not bound to give to the public your customizations).
So if you don't buy the business supported version you don't need to register etc, etc
